apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokecanov-frontend
spec:
  selector:
    matchLabels:
      app: pokecanov-frontend
  template:
    metadata:
      labels:
        app: pokecanov-frontend
    spec:
      containers:
      - name: pokecanov-frontend
        image: candraburhanudin15/pokecanovfrontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000                           
        # livenessProbe:                            
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      # imagePullSecrets:
      #   - name: melissa-hol-group
---
apiVersion: v1
kind: Service
metadata:
  name: pokecanov-frontend-svc
spec:
  selector:
    app: pokecanov-frontend
  ports:
  - port: 80
    targetPort: 3000