name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with Dockerfile1
        uses: docker/build-push-action@v4
        with: 
          context: ./frontend
          dockerfile: dockerfile
          push: true 
          tags: candraburhanudin15/pokecanov:latest
        

      - name: Build and push Docker image with Dockerfile1
        uses: docker/build-push-action@v4
        with: 
          context: ./backend
          dockerfile: dockerfile
          push: true 
          tags: candraburhanudin15/pokecanov:latest
          